name: Node.js CI

on:
  push:
    branches:
      - main
      - master
      - 'feature/**'
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'  

      - name: Install dependencies
        run: yarn install  

      - name: Run tests
        id: test
        run: yarn test  

      - name: Notify success
        if: ${{ success() }}
        run: echo "All tests passed successfully."

      - name: Notify failure
        if: ${{ failure() }}
        run: echo "Tests failed. Please check the logs above to fix the issues."
